OpenTechSchool/websitenext

data/cities/de/leipzig.md
pages/[lang]/city/[slug].tsx

This should allow us to use Markdown in HTML files. Neat!

Allow HTML in Markdown files

---

README.md
components/Footer/Footer.tsx
components/Meta.tsx
package-lock.json
package.json
style/style.js

Introduce grid to make positioning on the website easier (allows different column width based on viewport size)
For mobile, I'd like to keep the links in the footer for now. (It's an easy way to jump to specific content)

Update footer, fixes #5

---

components/Footer/Footer.tsx
package-lock.json
translations/en.json

Adds strings to translation files
Follow up on: https://github.com/OpenTechSchool/websitenext/pull/7

Add footer strings to translation file

---

components/Section/TextSection.tsx
pages/[lang]/about.tsx
style/style-global.js
translations/en.json

Updates about page with same font sizes and fix translations strings.
We might scale it down again, but I want to match the existing design for now.

Small updates on about page

---

components/Section/ChapterSection.tsx
pages/[lang]/community.tsx
style/style-global.js
translations/en.json

Adds community page.
Content still needs to be updated.

Add community page, fixes #2

---

components/Header/Header.tsx
components/Section/ChapterSection.tsx
pages/[lang]/contribute.tsx
translations/en.json

Just add the page, no content yet.

Add contribute page, fixes #1

---

components/Footer/Footer.tsx
components/PageLayout/PageLayout.tsx
components/Section/ChapterSection.tsx
components/Section/TextSection.tsx
package-lock.json
package.json
pages/[lang]/community.tsx
pages/[lang]/contribute.tsx
pages/[lang]/index.tsx
style/style.js

I didn't see that we use material ui already when adding the grid.
Now replacing flexbox-grid with the already existing material ui grid.

Replace flexbox-grid with material UI grid

---

pages/[lang]/index.tsx
translations/en.json

Copy update for home page

---

components/Footer/Footer.tsx
components/Section/ChapterSection.tsx
components/Section/ContactSection.tsx
pages/[lang]/about.tsx
pages/[lang]/codeOfConduct.tsx
pages/[lang]/community.tsx
pages/[lang]/contribute.tsx
pages/[lang]/guides.tsx
pages/[lang]/imprint.tsx
pages/[lang]/index.tsx
translations/en.json

Add links, cleanup

---

components/Footer/Footer.tsx
components/Header/Header.tsx
components/Section/ChapterSection.tsx
pages/[lang]/community.tsx
pages/[lang]/contribute.tsx
pages/[lang]/guides.tsx
pages/[lang]/index.tsx

See https://nextjs.org/docs/old#dynamic-routing

Fix client-side routing for dynamic routes

---

.eslintrc.js
components/Button/OutlineButton.tsx
components/CityHero/CityHero.tsx
components/Events.js
data/cities/en/berlin.md
data/cities/en/leipzig.md
data/cities/en/zurich.md
next.config.js
package-lock.json
package.json
pages/[lang]/city/[slug].js
style/style-global.js
translations/en.json

issue  #14
So far is visible just on chapter page

Events component

---

components/CityHero/CityHero.tsx
components/Section/ContactSection.tsx
package-lock.json
package.json
pages/[lang]/guides.tsx

- simplify build scripts, using different package (concurrency vs npm-run-all)
- fix lint errors and warnings
- add precommit Linting hook

Improve startup workflow

---

components/Footer/Footer.tsx

On mobile the footer items where not aligned correctly.

Fix footer

---

components/Events.js

Add city name to events box

---

components/Header/Header.tsx
components/Layout/Layout.tsx
components/Section/SocialMediaSection.tsx
components/Section/TextSection.tsx

Mobile menu

---

pages/[lang]/contribute.tsx
translations/en.json

Update contribute page

---

components/Section/TextSection.tsx
pages/[lang]/community.tsx
translations/en.json

Update community page

---

pages/[lang]/codeOfConduct.tsx

Just copied it from https://www.opentechschool.org/code-of-conduct/

Add code of conduct #61

---

style/style.js

https://material-ui.com/customization/default-theme/?expand-path=$.breakpoints.values

Sync media query values with Material UI theme - fixes #57

---

components/Footer/Footer.tsx

As suggested in #92 adding the copright year range 2012-2020

Update copyright year range in footer, closes #92

---

components/Header/Masthead.tsx

Handle squid position better on big screens

Fix masthead squid position

---

components/CityHero/CityHero.tsx
pages/[lang]/city/[slug].js

Fix a few issues we were seeing here: https://github.com/OpenTechSchool/websitenext/pull/100

Fixes for zurich page

---

components/Header/Masthead.tsx
style/style-global.js
translations/en.json

Update of this section copy:
Issue https://github.com/OpenTechSchool/websitenext/issues/69

OTS intro update

---

components/Section/ChapterSection.tsx
pages/[lang]/community.tsx
pages/[lang]/guides.tsx
pages/[lang]/index.tsx
translations/en.json

* modified ChapterSection: added new props for title and Booleans to show/hide active or inactive chapters
* added some text and a list with inactive chapters to Guides page

#43 add section Inactive Chapters to Guides page

---

components/Section/SocialMediaSection.tsx
data/cities/de/leipzig.md
data/cities/en/leipzig.md
pages/cities/[slug].js

Fixes #147
Note: The instagram.com/opentechschool IG account was blank, so I used instagram.com/opentechschool_leipzig . Please let me know if I need to change the address.

add instagram icon

---

translations/en.json

typo correction

---

data/cities/de/leipzig.md
data/cities/en/leipzig.md

Link was outdated, updating it

Fix slack link
